#include <xtl.h>
#include <xui.h>
#include <xuiapp.h>
#include <xuirender.h>
#include <xgraphics.h>
#include <xuianimate.h>
#include <xavatar.h>
#include <xmedia2.h>
#include <AtgApp.h>
#include <AtgFont.h>
#include <AtgInput.h>
#include <AtgMesh.h>
#include <AtgResource.h>
#include <AtgUtil.h>
#include <AtgDebugDraw.h>
#include <fstream>
#include <string>
#include <iostream>
#include <iomanip>
#include <sstream>
#include <hash_map>
#include <map>
#include <vector>
#include <direct.h>
#include <stdio.h>
#include <algorithm>
#include <time.h>
#include <d3d9.h>
